<?php 
/**
 * @file
 * Adds a Flickr feed processor to the Feeds module.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function flickrfeeds_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_feeds_plugins().
 */
function flickrfeeds_feeds_plugins() {
  $info = array();
  $info['FlickrFeedsParser'] = array(
    'name' => 'Flickr parser',
    'description' => 'Parse Flickr feeds.',
    'help' => '',
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'FlickrFeedsParser',
      'file' => 'FlickrFeedsParser.inc',
      'path' => drupal_get_path('module', 'flickrfeeds'),
    ),
  );
  return $info;
}
